apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  PODINFO_UI_MESSAGE: {{ .Values.configmap.message | quote }}
  ENVIRONMENT: {{ .Values.configmap.environment | quote }}